# -*- coding: utf-8 -*-
"""random_forest_reg_classifier

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zVNlLmfCzp2NRhYacM_1evqCkPYTP2SS
"""

import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()

digits

dir(digits)

import matplotlib.pyplot as plt 
plt.gray()
for i in range(4):
  plt.matshow(digits.images[i])

df =pd.DataFrame(digits.data)
df.head()

df['target'] = digits.target
df.head()

digits.target_names

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop(['target'],axis = 'columns'),digits.target,test_size = 0.2)

x_train.shape

x_test.shape

y_train.shape

y_test.shape

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

model.fit(x_train,y_train)

model.score(x_train,y_train)

model.score(x_test,y_test)

