# -*- coding: utf-8 -*-
"""random forest regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N3x4s2jgxp6qIsYMI4Jlr-KjN64PAoHn
"""

import pandas as pd

df = pd.read_csv(r"/content/drive/MyDrive/supervised learning project data /bengaluru_house_prices.csv")

df.head()

x = df.drop('price',axis = 'columns')

x

y = df['price']
y

from sklearn.preprocessing import LabelEncoder
le_area_type_availability  = LabelEncoder
le_availability = LabelEncoder
le_location = LabelEncoder
le_size = LabelEncoder
le_society = LabelEncoder
le_total_sqft = LabelEncoder
le_bath = LabelEncoder
le_balcony = LabelEncoder

x['area_type_n'] = le_area_type_availability.fit_transform(x['area_type'], target)
x['availability_n'] = le_availability.fit_transform(x['availability'], target)
x['location_n'] = le_location.fit_transform(x['location'], target)
x['size_n'] = le_size.fit_transform(x['size'], target)
x['society_n'] = le_society.fit_transform(x['society'], target)
x['total_sqft_n'] = le_total_sqft.fit_transform(x['total_sqft'], target)
x['bath_n'] = le_bath.fit_transform(x['bath'], target)
x['balcony_n'] = le_balcony.fit_transform(x['balcony'], target)

x

x_n = x.drop(['area_type','availability','location','size','society','total_sqft','bath','balcony'],axis = 'columns')

x_n

from sklearn.model_selection import train_test_split

x_train, x_test, y_train , y_test =  train_test_split(x_n,y,test_size = 0.2)

x_train.shape

x_test.shape

y_train.shape

y_test.shape

"""#USING RANDOM FOREST ENSEMBLE LEARNING """

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators = 100)

model.fit(x_train,y_train)

model.score(x_train,y_train)

"""# using predict method """

x_test.iloc[-1,:]

model.predict([x_test.iloc[-1,:]])

y_test.iloc[-1]

y_pred = model.predict(x_test)
 y_pred

y_test



