# -*- coding: utf-8 -*-
"""support vector mechanism

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12IH-9qOUAbcG1pYmmEEprsB8wgtNbSZX
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
iris = load_iris()

dir(iris)

iris.feature_names

df = pd.DataFrame(iris.data, columns = iris.feature_names)

df.head()

df["target"] = iris.target
df.head()

df["flower_names"] = df.target.apply (lambda x : iris.target_names[x])
df.head()

iris.target_names

df1 = df[df.target==0]
df2 = df[df.target==1]
df3 = df[df.target==2]

df1.head()

df2.head()

df3.head()

plt.xlabel('sepal length (cm)')
plt.ylabel('sepal width (cm)')

plt.scatter(df1['sepal length (cm)'],df1['sepal width (cm)'],color = 'green',marker = "+")
plt.scatter(df2['sepal length (cm)'],df2['sepal width (cm)'],color = 'red',marker = "+")
plt.scatter(df3['sepal length (cm)'],df3['sepal width (cm)'],color = 'blue',marker = "+")

plt.xlabel('petal length (cm)')
plt.ylabel('petal width (cm)')

plt.scatter(df1['petal length (cm)'],df1['petal width (cm)'],color = 'green',marker = "+")
plt.scatter(df2['petal length (cm)'],df2['petal width (cm)'],color = 'red',marker = "+")
plt.scatter(df3['petal length (cm)'],df3['petal width (cm)'],color = 'blue',marker = "+")

x = df.drop(['target','flower_names'],axis = 'columns')
x

y = df.target
y

from sklearn.model_selection import train_test_split
x_train , x_test , y_train, y_test = train_test_split(x,y,test_size = 0.3)

len(x_train)

len(x_test)

len(y_train)

len(y_test)

from sklearn.svm import SVC
model = SVC()

model.fit(x_train,y_train)

model.score(x_train,y_train)

model.predict([[5.1,2.3,5.9,1.8]])

